# Generated by Django 3.1.7 on 2021-04-15 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='ACURA', max_length=30)),
                ('modelo', models.CharField(default='XWZ', max_length=30)),
                ('ano', models.IntegerField(default=2021)),
                ('status', models.CharField(default='BOM', max_length=10)),
                ('cor', models.CharField(default='VERMELHO', max_length=10)),
                ('combustivel', models.CharField(default='FLEX', max_length=10)),
                ('quilometragem', models.DecimalField(decimal_places=2, default=100, max_digits=10, max_length=12)),
                ('lucro', models.DecimalField(decimal_places=2, default=100, max_digits=10, max_length=12)),
                ('preco', models.DecimalField(decimal_places=2, default=100, max_digits=10, max_length=12)),
                ('margem_de_lucro', models.DecimalField(decimal_places=2, default=100, max_digits=10, max_length=12)),
                ('data_postada', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
