# Generated by Django 3.1.7 on 2021-04-16 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0002_datadb_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadb',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datadb',
            name='combustivel',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='datadb',
            name='cor',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='datadb',
            name='lucro',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=12),
        ),
        migrations.AlterField(
            model_name='datadb',
            name='marca',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='datadb',
            name='margem_de_lucro',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=12),
        ),
        migrations.AlterField(
            model_name='datadb',
            name='modelo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='datadb',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=12),
        ),
        migrations.AlterField(
            model_name='datadb',
            name='quilometragem',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=12),
        ),
        migrations.AlterField(
            model_name='datadb',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
