# Generated by Django 3.1.7 on 2021-04-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20210417_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadb',
            name='localidade',
            field=models.CharField(default='Piracicaba', max_length=30),
        ),
    ]
