# Generated by Django 3.1.7 on 2021-04-24 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20210419_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadb',
            name='combustivel',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='datadb',
            name='localidade',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='datadb',
            name='lucro',
            field=models.DecimalField(decimal_places=2, error_messages={'decimal_places': 'Favor so por 2 casas decimais.', 'max_digits': 'Favor inserir um lucro menor.', 'required': 'Favor inserir o lucro'}, max_digits=10, max_length=12, validators=[django.core.validators.MaxValueValidator(99999999, 'Favor inserir valor menor')]),
        ),
        migrations.AlterField(
            model_name='datadb',
            name='preco',
            field=models.DecimalField(decimal_places=2, error_messages={'decimal_places': 'Favor so por 2 casas decimais.', 'max_digits': 'Favor inserir um lucro menor.', 'required': 'Favor inserir o lucro'}, max_digits=10, max_length=12, validators=[django.core.validators.MinValueValidator(1000.0, 'Favor inserir vendas acima de 1000 reais'), django.core.validators.MaxValueValidator(99999999, 'Favor inserir valor menor')]),
        ),
        migrations.AlterField(
            model_name='datadb',
            name='quilometragem',
            field=models.DecimalField(decimal_places=2, error_messages={'decimal_places': 'Favor so por 2 casas decimais.', 'max_digits': 'Favor inserir uma kilometragem menor.', 'required': 'Favor inserir a quilometragem'}, max_digits=10, max_length=12, validators=[django.core.validators.MinValueValidator(0, 'Não existe quilometragem negativa'), django.core.validators.MaxValueValidator(99999999, 'Favor inserir valor menor')]),
        ),
        migrations.AlterField(
            model_name='datadb',
            name='status',
            field=models.CharField(max_length=1),
        ),
    ]
