# Generated by Django 3.1.7 on 2021-04-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_datadb_motor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadb',
            name='motor',
            field=models.CharField(error_messages={'required': 'Favor inserir um modelo'}, max_length=60),
        ),
    ]
