# Generated by Django 3.1.7 on 2021-04-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20210426_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadb',
            name='combustivel',
            field=models.CharField(choices=[('G', 'Gasolina'), ('E', 'Etanol'), ('G', 'GNV'), ('D', 'Diesel'), ('F', 'Flex')], max_length=1),
        ),
        migrations.AlterField(
            model_name='datadb',
            name='localidade',
            field=models.CharField(choices=[('P', 'Piracicaba'), ('L', 'Limeira')], max_length=1),
        ),
        migrations.AlterField(
            model_name='datadb',
            name='motor',
            field=models.CharField(error_messages={'required': 'Favor inserir um motor'}, max_length=60),
        ),
        migrations.AlterField(
            model_name='datadb',
            name='status',
            field=models.CharField(choices=[('E', 'Excelente'), ('B', 'Bom'), ('M', 'Mediano'), ('R', 'Ruim'), ('T', 'Terrível')], max_length=1),
        ),
    ]
