# Generated by Django 3.1.7 on 2021-04-28 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20210426_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadb',
            name='lucro',
            field=models.DecimalField(decimal_places=2, max_digits=12, max_length=12, validators=[django.core.validators.MaxValueValidator(99999999, 'Favor inserir valor menor')]),
        ),
        migrations.AlterField(
            model_name='datadb',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=12, max_length=12, validators=[django.core.validators.MinValueValidator(1000.0, 'Favor inserir vendas acima de 1000 reais'), django.core.validators.MaxValueValidator(99999999, 'Favor inserir valor menor')]),
        ),
        migrations.AlterField(
            model_name='datadb',
            name='quilometragem',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=12, validators=[django.core.validators.MinValueValidator(0, 'Não existe quilometragem negativa'), django.core.validators.MaxValueValidator(99999999, 'Favor inserir valor menor')]),
        ),
    ]
