# Generated by Django 3.1.7 on 2021-04-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='ano',
            field=models.IntegerField(default=2021),
        ),
        migrations.AddField(
            model_name='dado',
            name='combustivel',
            field=models.CharField(default='FLEX', max_length=10),
        ),
        migrations.AddField(
            model_name='dado',
            name='cor',
            field=models.CharField(default='VERMELHO', max_length=10),
        ),
        migrations.AddField(
            model_name='dado',
            name='lucro',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, max_length=12),
        ),
        migrations.AddField(
            model_name='dado',
            name='marca',
            field=models.CharField(default='ACURA', max_length=30),
        ),
        migrations.AddField(
            model_name='dado',
            name='margem_de_lucro',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, max_length=12),
        ),
        migrations.AddField(
            model_name='dado',
            name='modelo',
            field=models.CharField(default='XWZ', max_length=30),
        ),
        migrations.AddField(
            model_name='dado',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, max_length=12),
        ),
        migrations.AddField(
            model_name='dado',
            name='quilometragem',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, max_length=12),
        ),
        migrations.AddField(
            model_name='dado',
            name='status',
            field=models.CharField(default='BOM', max_length=10),
        ),
    ]
