# Generated by Django 3.1.7 on 2021-04-10 18:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dado', '0002_auto_20210410_1232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dado',
            new_name='DadoDB',
        ),
    ]
