# Generated by Django 3.1.7 on 2021-04-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='setor',
            field=models.CharField(choices=[('R', 'Revendedora'), ('C', 'Concessionária')], max_length=1),
        ),
    ]
