# Generated by Django 3.1.7 on 2021-04-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20210424_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nome_da_empresa',
            field=models.CharField(default='IVG', error_messages={'required': 'Favor inserir um nome'}, max_length=60),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='setor',
            field=models.CharField(choices=[('R', 'Revendedora')], max_length=1),
        ),
    ]
