# Generated by Django 3.1.7 on 2021-04-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20210428_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nome_da_empresa',
            field=models.CharField(error_messages={'required': 'Favor inserir um nome'}, max_length=60),
        ),
    ]
