# Generated by Django 3.1.7 on 2021-05-04 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20210428_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='potato', max_length=30)),
                ('texto', models.CharField(default='potato', max_length=500)),
                ('grafico1', models.ImageField(upload_to='')),
                ('grafico2', models.ImageField(upload_to='')),
                ('grafico3', models.ImageField(upload_to='')),
                ('grafico4', models.ImageField(upload_to='')),
                ('filtro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
