# Generated by Django 3.1.7 on 2021-05-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20210504_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacao',
            name='grafico1',
            field=models.ImageField(upload_to='graficos_recomendados'),
        ),
        migrations.AlterField(
            model_name='recomendacao',
            name='grafico2',
            field=models.ImageField(upload_to='graficos_recomendados'),
        ),
        migrations.AlterField(
            model_name='recomendacao',
            name='grafico3',
            field=models.ImageField(upload_to='graficos_recomendados'),
        ),
        migrations.AlterField(
            model_name='recomendacao',
            name='grafico4',
            field=models.ImageField(upload_to='graficos_recomendados'),
        ),
    ]
