# Generated by Django 3.1.7 on 2021-05-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20210504_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendacao',
            name='grafico1',
        ),
        migrations.RemoveField(
            model_name='recomendacao',
            name='grafico2',
        ),
        migrations.RemoveField(
            model_name='recomendacao',
            name='grafico3',
        ),
        migrations.RemoveField(
            model_name='recomendacao',
            name='grafico4',
        ),
        migrations.AlterField(
            model_name='recomendacao',
            name='texto',
            field=models.TextField(max_length=500),
        ),
    ]
