# Generated by Django 3.1.7 on 2021-05-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_recomendacao_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacao',
            name='image1',
            field=models.ImageField(upload_to='graficos_recomendados'),
        ),
    ]
