# Generated by Django 3.1.7 on 2021-05-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20210504_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendacao',
            name='image1',
        ),
    ]
