# Generated by Django 3.1.7 on 2021-04-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_IVG', '0002_auto_20210406_1310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dado',
        ),
    ]
